source 'https://rubygems.org'

gem 'rails', '~> 3.2.18'
gem 'wongi-engine', :git => 'git://github.com/ulfurinn/wongi-engine.git', branch: "master"
gem 'gon', '~> 5.1.1'
gem 'jquery-rails', '~> 3.1.0'


gem "font-awesome-rails", '~> 4.1.0.0'
gem 'simple_form', '~> 2.1.1'
gem 'thin', '~> 1.6.2'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'autoprefixer-rails', '~> 2.1.1.20140710'
gem 'acts_as_list', '~> 0.4.0'
gem 'sqlite3', '~> 1.3.9'

group :development do
  gem "better_errors"
  gem "binding_of_caller"
  gem 'railroady'
end


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'jquery-ui-rails', '~> 4.2.1'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

 

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
